### ISSUE TITLE
Unable to locate element: .slateTextArea-1Mkdgw

### ISSUE THREAD

**Issue by ouroboros998** [RandomBananazz/AutoWaifuClaimerV3#1]

**Comment by JasonYuan869** [comment]
Interesting. I seemed to have forgotten to catch a `NoSuchElementException` thrown by Selenium on that line, which I have now addressed in 28341fb.

Are you sure you put the right login information to `config.py`? If you did, try commenting out the headless option on line 41 of `browsers.py` and seeing if the browser successfully logs in. If it does, then that is *really* weird.

Can you tell me what Python version you're running?

**Comment by ouroboros998** [comment]
The python version that I'm using is 3.9,
I just updated to the new code still the same error. 
It does login successfully to the website, the headless line "-headless" did not work for me it does not open the browser I tried commenting out the headless option on line 41 still the browser did not open,  so I replaced it with "/path/to/firefox -P my-profile -headless" the browser opened but I got the same error again: Unable to locate element: .slateTextArea-1Mkdgw

**Comment by JasonYuan869** [comment]
That is really weird... I just downloaded Python 3.9 on my Windows system and it seems to work fine. I also tried modifying the `options.add_argument()` line top put my Firefox binary and it also works fine (interestingly it's not headless despite the `-headless` option).

Can you try just commenting out the `options.add_argument()` line and instead change the following line to:
`self.driver = webdriver.Firefox(executable_path=config.WEB_DRIVER_PATH, options=options, firefox_binary="/path/to/firefox")`

**Comment by ouroboros998** [comment]
Message: binary is not a Firefox executable
I don't know what to do now xD

**Comment by JasonYuan869** [comment]
OS?

**Comment by ouroboros998** [comment]
Windows 10

**Comment by JasonYuan869** [comment]
In that case, make sure that you're inputting the path using double backslashes. For example: `"C:\\Program Files\\Mozilla Firefox\\firefox.exe"`.

**Comment by JasonYuan869** [comment]
> In that case, make sure that you're inputting the path using double backslashes. For example: `"C:\\Program Files\\Mozilla Firefox\\firefox.exe"`.

Same goes with the geckodriver executable in `config.py`, unless it's in the main project folder.
